name: CI/CD de Front da turma 3

on: 
  push:
    branches:
      - turma3

jobs: 
  ci-cd-front:
    runs-on: ubuntu-latest
    steps: 

    - name: Checkot out code 
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Create env file
      run: |
        touch .env
        echo REACT_APP_SERVER_URL=${{ secrets.CRA_URL }} >> .env
        cat .env

    - name: Install dependencies
      run: npm i

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        #args: --severity-threshold=high
        command: monitor

    - name: Run test with coverage
      run: npm run lint:cov

    - name: Run test with coverage
      run: npm run test:cov

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync S3
      run: aws s3 sync build s3://adora-staging --acl public-read

    - name: Invalidate Cloudfront
      run: aws cloudfront create-invalidation --distribution-id E3NCHTE4ORA2QL --paths "/*" --no-cli-pager